name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checka ut repot
      - uses: actions/checkout@v3

      
      - name: Install pytest
        run: pip install pytest

      
      - name: Run unit tests
        run: pytest

      
      - name: Run a one-line script
        run: echo Hello, world!

      
      - name: Copy to dist
        run: |
          mkdir dist
          cp web/index.html dist/index.html
          cp web/data.json dist/data.json
          cp web/script.js dist/script.js

      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
